=== Jeffreyhung/NCHU_XML/WebContent/form.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
    <xs:element name="application" type="application_type"/>
		<xs:complexType name="application_type">
			<xs:sequence>
				<xs:element name="org" type="xs:string"/>
				<xs:element name="activity" type="xs:string"/>
				<xs:element name="location" type="xs:string"/>
				<xs:element name="mixer" type="xs:string"/>
				<xs:element name="console" type="xs:string" />
				<xs:element name="speaker">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="01"/>
							<xs:maxInclusive value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="mic">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="01"/>
							<xs:maxInclusive value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="par">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="01"/>
							<xs:maxInclusive value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="led">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="01"/>
							<xs:maxInclusive value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="wire">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="01"/>
							<xs:maxInclusive value="20"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="line">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="01"/>
							<xs:maxInclusive value="20"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="price" type="xs:integer"/>				
			</xs:sequence>
			<xs:attribute name="number" type="xs:integer"/>
			<xs:attribute name="date" type="xs:string"/>
		</xs:complexType>
</xs:schema>

=== Jeffreyhung/NCHU_XML/WebContent/equip.xml
<?xml version="1.0" encoding="UTF-8"?>
<application number="000" date="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xsi:noNamespaceSchemaLocation="http://140.120.78.192:8090/EquipManage/form.xsd">
    <org></org>
	<activity></activity>
	<location></location>
	<mixer>O1v96i</mixer>
	<console>C24</console>
	<speaker>10</speaker>
	<mic>10</mic>
	<par>5</par>
	<led>10</led>
	<wire>15</wire>
	<line>15</line>
	<price>0</price>
</application>

=== Jeffreyhung/NCHU_XML/WebContent/xmls/20170621914.xml
<?xml version="1.0" encoding="UTF-8"?><application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" date="2017-06-21" number="20170621914" xsi:noNamespaceSchemaLocation="http://140.120.78.192:8090/EquipManage/form.xsd">
    <org>資管系</org>
	<activity>送舊</activity>
	<location>小禮堂</location>
	<mixer>BX2442</mixer>
	<console>KK256</console>
	<speaker>4</speaker>
	<mic>8</mic>
	<par>8</par>
	<led>6</led>
	<wire>18</wire>
	<line>1</line>
	<price>2100</price>
</application>

=== Jeffreyhung/NCHU_XML/WebContent/xmls/20170617613.xml
<?xml version="1.0" encoding="UTF-8"?><application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" date="2017-06-17" number="20170617613" xsi:noNamespaceSchemaLocation="http://140.120.78.192:8090/EquipManage/form.xsd">
    <org>電機系</org>
	<activity>系卡</activity>
	<location>惠蓀堂</location>
	<mixer>O1v96i</mixer>
	<console>KK1024p</console>
	<speaker>4</speaker>
	<mic>6</mic>
	<par>4</par>
	<led>4</led>
	<wire>17</wire>
	<line>19</line>
	<price>2100</price>
</application>

=== Jeffreyhung/NCHU_XML/WebContent/xmls/20170627782.xml
<?xml version="1.0" encoding="UTF-8"?><application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" date="2017-06-27" number="20170627782" xsi:noNamespaceSchemaLocation="http://140.120.78.192:8090/EquipManage/form.xsd">
    <org>單位</org>
	<activity>活動</activity>
	<location>地點</location>
	<mixer>BX2442</mixer>
	<console>KK1024p</console>
	<speaker>4</speaker>
	<mic>2</mic>
	<par>2</par>
	<led>2</led>
	<wire>10</wire>
	<line>10</line>
	<price>1300</price>
</application>
